userモデル以外のテストを書いた
g-fujioka/daily_report pull request #26
Opened 2017-06-02 06:36 UTC by g-fujioka

closed #25 
* report, comment, departmentモデルのテストを書いた
* userモデルにdependent: :destroyのテストを書いた

2017-06-02 06:41 UTC, kazuhisa commented
commitの粒度が良いですね 👍

2017-06-02 06:47 UTC, kazuhisa commented
新規のプルリクを出す時はプルリクを出すブランチ(ここではmaster)から分岐させて、新たなブランチを作成して下さい。

2017-06-02 06:57 UTC, kazuhisa requested changes
@g-fujioka 
修正お願いします。

2017-06-02 06:57 UTC, kazuhisa commented on spec/models/report_spec.rb
>  end
```ruby
default_scope -> {order(created_at: :DESC)}
```
このテストが入っていないかな？複数のデータを登録して並び順を検証してみて下さい。

2017-06-02 06:57 UTC, kazuhisa commented on spec/models/department_spec.rb
> +end
```ruby
enum state: { invalidate: false, activate: true }
```
この検証を考えてみよう。
プログラムの仕様を変更した時に、テストが落ちるようにしたい。
どういう検証を行えばいいかな？

2017-06-02 06:57 UTC, kazuhisa commented on spec/models/user_spec.rb
> +    it 'ユーザーを削除すると日報も削除すること' do
「日報も削除されること」のほうが自然かな

2017-06-02 06:57 UTC, kazuhisa commented on spec/models/user_spec.rb
> +    it 'ユーザーを削除するとコメントも削除すること' do
「コメントも削除されること」のほうが自然かな

2017-06-02 09:08 UTC, g-fujioka commented
@kazuhisa 
修正を行いました。

2017-06-05 00:28 UTC, kazuhisa approved these changes
いい感じです
![](http://i.imgur.com/Tdfkn8M.gif)

2017-06-05 00:28 UTC, merged