ユーザーのインテグレーションテストを作成
g-fujioka/daily_report pull request #32
Opened 2017-06-05 08:40 UTC by g-fujioka

closed #29 
* ユーザーのインテグレーションテストを作成
* ユーザーフォームのチェックボックスの値を修正

2017-06-05 09:02 UTC, kazuhisa requested changes
以上です。

2017-06-05 09:02 UTC, kazuhisa commented on spec/requests/users_spec.rb
> +  let(:user) { FactoryGirl.create(:user, email: 'cat2@example.com', admin: false, department: department) }
`admin_user`や`user`は遅延実行で作成させるよりも、頭で作っていたほうが今回のテストは書きやすいと思います。letをlet!に変えて試してみて下さい。

2017-06-06 00:10 UTC, g-fujioka commented
@kazuhisa 
admin_userとuserをlet!に変更しました。

2017-06-06 00:53 UTC, kazuhisa approved these changes
OKです。
![](https://49.media.tumblr.com/ff8a132242ef963c0262604b0e1522bd/tumblr_ny6rt0ANqE1rylzllo1_400.gif)

2017-06-06 00:53 UTC, merged